# -*- coding: utf-8 -*-
"""Copy of  Python class 1. int float string ipynb july 7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nUHB237aokF_9qNw9L-76PRMagEKfYdu
"""

datatypes varaibles datatypes in built functions

a=10
b=20.6
name="data"

a=10
## except _ other special characters are not allowed
a=10
### while creating variables it should not start with a number

import keyword
print(keyword.kwlist)

async=20

#### Reserve words, keywords we cannot use these as variable names
### use the right name for variable instead of using a,b,c like this names should
### be retail,sales,units, trasactions,age,name,geneder

pip install packagename

int, float, string

a=10
print(a)
print(type(a))

a=10.2
type(a)

name=" data science machine learning "
type(name)

int,float,str

int('name')

type conversion:

  int --> float,string
  float ---> int,string
  string cannot be int,float

float("data")

type(2+3j)

a=2+3j
a.real

a.imag

x="data science"

x

x="data engineering"
print(x)

x[-4:-2]

x

print(x[-11:])
print(x[:4])

x[-11:4]

len(x)
x[20]

"""```python
text = "Edukron Data Science and Data Engineering Batch 2026"
```

# Python String Indexing Questions

1. Write the indexing expression to print **"Edukron"**.
   ```
   Answer: print(text[0:7])
           print(text[-52:-45])
   ```

2. Write the indexing expression to print **"Data"** (first occurrence).
   ```
   Answer: print(text[8:12])
           print(text[-44:-40])
   ```

3. Write the indexing expression to print **"Science"**.
   ```
   Answer: print(text[13:20])
   ```     print(text[-39:-32])

4. Write the indexing expression to print **"and"**.
   ```
   Answer: print(text[21:24])
           print(text[-31:-28])
   ```

5. Write the indexing expression to print **"Data Engineering"**.
   ```
   Answer: print(text[25:41])
           print(text[-27:-11])
   ```

6. Write the indexing expression to print **"Engineering"**.
   ```
   Answer: print(text[30:41])
           print(text[-22:-11])
   ```

7. Write the indexing expression to print **"Batch"**.
   ```
   Answer: print(text[42:47])
           print(text[-10:-5])
   ```

8. Write the indexing expression to print **"2026"**.
   ```
   Answer: print(text[48:52])
           print(text[-4:])

   ```

9. Write the indexing expression to print **"Science and Data"**.
   ```
   Answer: print(text[13:29])
           print(text[-39:-23])
   ```

10. Write the indexing expression to print **"Data Science and Data Engineering Batch"**.
    ```
    Answer: print(text[8:47])
            print(text[-44:-5])
    ```
```
"""